# Package Overview
package_name: regression_model

# Data Files
training_data_file: train.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (sale price)
target: survived

pipeline_name: regression_model
pipeline_save_file: regression_model_output_v



features:
  - pclass
  - sex
  - age
  - sibsp
  - parch
  - fare
  - cabin
  - embarked
  - title
  - name
  - body
  - home.dest
  - ticket
  - boat
  

# set train/test split
test_size: 0.2

# to set the random seed
random_state: 0

C: 0.0005


categorical_vars:
  - sex
  - embarked
  - title
  - name
  - home.dest
 


